### ISSUE TITLE
Incorrect Shape of Kernel?

### ISSUE THREAD

**Issue by tkoch96** [JesperDramsch/keras-complex#4]
Hello,

I'm running into errors regarding the shape of the kernel for the complex convolution. In the ComplexConv class you have:

![image](https://user-images.githubusercontent.com/10697990/82153120-8cba6000-9833-11ea-833a-7a5a6be2c189.png)

Say the number of filters is 8, each with 2x2 shape and the input size is 10x10x2. Then self.kernel_shape will be 2x2x1x8. However the initializer is generating something of shape 2x2x1x16 (real and complex). Shouldn't kernel shape also be 2x2x1x16, for the purposes of passing into self.add_weight?

**Comment by JesperDramsch** [comment]
The weights should still function for complex kernels, so one weight for two feature maps. Otherwise, there'd be no difference to just having a real-valued network with two inputs.

**Comment by tkoch96** [comment]
I don't fully understand what you're saying above. What makes the layer complex is the forced complex multiplication structure (a_r * b_r - a_i*b_i, a_i*b_r + a_r*b_i).

The problem I'm seeing is that the function add_weight expects kernel_shape to be the same shape as whatever is generated in initializer. However the initializer generates something 2x larger on the filter dimension so an error is thrown.

**Comment by JesperDramsch** [comment]
Would you mind sharing a code example so I can reproduce the error? It's a bit abstract for me right now. It would help me work through the issue. Thank you for your help here.

In the end, this is a port of the original work in Theano, so it's possible I inherited some things that have to be ironed out.

**Comment by Ouwen** [comment]
This is an error I see from the original Theano code as well. The fix would be to ensure that the kernel shape matches the init shape. Either by halving the init features or by doubling the filters.

@JesperDramsch were you able to compile a model with the ComplexConv of rank 2 function in tensorflow v1?

**Comment by tkoch96** [comment]
I should have updated with progress. I got it working in Tensorflow V2 by adding little modifications here and there for my needs. I'm not sure if it would be useful to share everything, since it probably only works the specific settings that I use it for, but one big change was (referring to my original linked code).

`actual_kernel_shape = list(self.kernel_shape)`
`actual_kernel_shape[-1] *= 2`

`self.kernel = self.add_weight(`
`"kernel", list(actual_kernel_shape), initializer=kern_init, regularizer=self.kernel_regularizer, constraint=self.kernel_constraint,`
`)`

**Comment by Blubbaa** [comment]
I am trying to update the code for tf 2.3, by switching to the `tensorflow.keras` API. Some keras utility functions were removed, moved to different modules or renamed. I soemhow managed to get a working version (currently only judging by working unittests) for 2.3 and created a PR #9.

I ran into the same problem regarding kernel shape, but the suggestion from @tkoch96 needed another change in the complex initializer in order to work:
https://github.com/JesperDramsch/keras-complex/blob/331758e0420e27009ced3a0991828d443c4263fb/complexnn/init.py#L240-L243

Maybe someone can review the changes and see if it makes sense, as by now I only tested it using the few unit tests in the repository. @tkoch96, would you mind comparing to your working code and see if you spot any issues / differences?

**Comment by JesperDramsch** [comment]
Changes accepted in #9
